export default defineEventHandler(async () => {
  await useDb().delete(tables.users).all()
  await useDb().delete(tables.brands).all()
  await useDb().delete(tables.tags).all()
  await useDb().delete(tables.categories).all()
  await useDb().delete(tables.products).all()
  await useDb().delete(tables.slider).all()
  await useDb().delete(tables.about).all()
  await useDb().delete(tables.attributes).all()
  await useDb().delete(tables.options).all()
  await useDb().delete(tables.variants).all()
  await useDb().delete(tables.orders).all()
  await useDb().delete(tables.orderProducts).all()
  await useDb().delete(tables.returnOrders).all()
  await useDb().delete(tables.returnOrderProducts).all()
  await useDb().delete(tables.offers).all()
  await useDb().delete(tables.offerProducts).all()
  await useDb().delete(tables.visitors).all()
  await useDb().delete(tables.contacts).all()
  return 'All brands with logos added successfully.'
})
