const icons = {
  // about: 'ix:about',
  returns: 'material-symbols:assignment-return-rounded',
  // terms: 'iconoir:page',
  policy: 'material-symbols:privacy-tip-outline-rounded',
  add: 'i-ci-add-row',
  // alert: 'i-lucide-shield-alert',
  arrowDown: 'i-typcn-arrow-down',
  arrowDown2: 'i-bxs-down-arrow',
  arrowLeft: 'i-iconamoon-arrow-left-2-light',
  arrowRight: 'i-iconamoon-arrow-right-2-light',
  arrowUp: 'i-typcn-arrow-up',
  arrowRightLine: 'i-typcn-arrow-right',
  back: 'i-icon-park-outline-back',
  back2: 'i-mingcute-back-fill',
  // bell: 'i-lucide-bell',
  // birthday: 'i-mingcute-birthday-2-line',
  // briefcase: 'i-lucide-briefcase',
  brand: 'tabler:brand-azure',
  color: 'i-cil-color-fill',
  // camera: 'i-heroicons-camera',
  // cancel: 'solar:close-circle-outline',
  voucher: 'i-hugeicons-coupon-02',
  // card: 'ic:baseline-credit-card',
  // calendar: 'i-lucide-calendar',
  // cart: 'tabler:shopping-cart',
  cate: 'tabler:brand-blackberry',
  circle: 'mdi:circle-medium',
  // circleCheck: 'iconoir:check-circle-solid',
  // circlecheck: 'i-lucide-circle-check',
  // city: 'material-symbols:location-city',
  clear: 'i-icon-park-twotone-clear-format',
  // clock: 'solar:alarm-outline',
  // contact: 'material-symbols-light:perm-contact-calendar-outline-sharp',
  // copy: 'i-lucide-copy',
  // check: 'i-lucide-check',
  // circlecek: 'i-lucide-check-circle',
  // circlecross: 'i-lucide-x-circle',
  // country: 'mdi:ski-cross-country',
  // credit: 'i-material-symbols-credit-card-outline',
  // cookie: 'i-lucide-cookie',
  // chart: 'i-lucide-bar-chart',
  // delete: 'tabler:trash',
  // delivered: 'icon-park-outline:check-correct',
  // detail: 'lucide:list',
  dollar: 'solar:dollar-bold',
  dot: 'lucide:dot',
  // dotMenu: 'i-iconamoon-menu-kebab-vertical-fill',

  // edit: 'tabler:edit',
  edit2: 'material-symbols:edit',

  // email: 'material-symbols-light:mail',
  empty: 'solar:file-smile-bold',
  error: 'tabler:info-triangle-filled',
  // eye: 'tabler:eye',
  eyeOff: 'material-symbols-light:visibility-off-rounded',
  facebook: 'line-md:facebook',
  fillheart: 'solar:heart-bold',
  // filter: 'i-rivet-icons-filter',
  funnel: 'tabler:chart-funnel-filled',
  gender: 'i-mdi-gender-male',
  // gift: 'i-heroicons-gift',
  // google: 'i-bxl-google',
  // globe: 'i-lucide-globe',

  heartOutline: 'i-mdi-heart-outline',
  // history: 'i-material-symbols-history',
  // home: 'tabler:brand-google-home',
  // image: 'i-lucide-image',
  // inbox: 'i-lucide-inbox',
  // info: 'i-lucide-info',
  instagram: 'line-md:instagram',
  linkedin: 'line-md:linkedin',
  loading: 'i-mingcute-loading-line',
  // locate: 'i-mage-location-fill',
  // location: 'i-heroicons-map-pin',
  // login: 'lucide:log-in',
  logo: 'i-ph-replit-logo-fill',
  logout: 'tabler:logout-2',
  // lock: 'i-lucide-lock',
  // list: 'i-lucide-clipboard-list',
  // mail: 'i-lucide-mail',
  // map: 'i-solar-map-bold',
  // order: 'lucide:shopping-bag',
  offer: 'i-streamline-discount-percent-coupon',
  orders: 'i-famicons:logo-buffer',
  password: 'i-mingcute-user-lock-line',
  // phone: 'i-heroicons-phone',
  profileUpdate: 'material-symbols:system-update-alt-rounded',
  process: 'lucide:loader',
  Processing: 'svg-spinners:12-dots-scale-rotate',
  product: 'tabler:brand-databricks',
  // profile: 'lucide:user-round',
  // package: 'i-lucide-package',
  pin: 'material-symbols:pin-outline-rounded',
  return: 'material-symbols:assignment-return',
  // reply: 'i-lucide-reply',
  // revenue: 'mingcute:chart-vertical-fill',
  remove: 'i-material-symbols-remove',
  // refresh: 'i-lucide-refresh-cw',
  save: 'mdi-light:content-save',
  // search: 'tabler:search',
  // send: 'i-lucide-send',
  // setting: 'i-uil-setting',
  // shipping: 'i-lucide-truck',
  // slash: 'tabler:slash',
  // slides: 'i-ph-slideshow',
  subject: 'i-carbon-document-subject',
  size: 'i-icons8-resize-four-directions',
  // smile: 'i-lucide-smile',
  // share: 'i-lucide-share',
  // shield: 'i-lucide-shield',
  street: 'streamline:street-road',
  // tag: 'solar:tag-price-bold',
  tick: 'material-symbols:fitbit-check-small-sharp',
  truck: 'material-symbols-light:delivery-truck-bolt-outline',
  twitter: 'line-md:twitter-x-alt',

  upload: 'i-ix-attachment-upload',
  // user: 'i-lucide-user',
  userPlus: 'i-mingcute-user-add-2-fill',
  // users: 'i-flowbite-users-group-solid',
  // wallet: 'i-lucide-wallet',
  whattsapp: 'tabler:brand-whatsapp',
  xFilled: 'tabler:xbox-x-filled',

  refunded: 'i-mdi-undo',
  // heart: 'i-heroicons-heart',
  heartFilled: 'i-heroicons-heart-solid',
  // handshake: 'i-lucide-handshake',
  // headphones: 'i-lucide-headphones',

}
export default defineAppConfig({
  ui: { icons },
  uiPro: {
    pageGrid: {
      base: 'relative grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4',
    },
  },
})
